services:

  postgres:
    image: postgres:16-alpine
    container_name: matricula_postgres_prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "3050:5432"
    volumes:
      - matricula_prod_data:/var/lib/postgresql/data
    networks:
      - matricula_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    image: ${DOCKER_HUB_USERNAME}/demo-ds-univalle:latest
    container_name: matricula_api_prod
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "8085:8085"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - matricula_network
    restart: unless-stopped

networks:
  matricula_network:
    driver: bridge

volumes:
  matricula_prod_data: